const mongoose = require("mongoose");

const contactSchema = new mongoose.Schema({
  ID: String,
  POST: String,
  COMMENTS: String,
  HONORIFIC: String,
  NAME: String,
  SECOND_NAME: String,
  LAST_NAME: String,
  PHOTO: String,
  LEAD_ID: String,
  TYPE_ID: String,
  SOURCE_ID: String,
  SOURCE_DESCRIPTION: String,
  COMPANY_ID: String,
  BIRTHDATE: String,
  EXPORT: String,
  HAS_PHONE: String,
  HAS_EMAIL: String,
  HAS_IMOL: String,
  DATE_CREATE: String,
  DATE_MODIFY: String,
  ASSIGNED_BY_ID: String,
  CREATED_BY_ID: String,
  MODIFY_BY_ID: String,
  OPENED: String,
  ORIGINATOR_ID: String,
  ORIGIN_ID: String,
  ORIGIN_VERSION: String,
  FACE_ID: String,
  ADDRESS: String,
  ADDRESS_2: String,
  ADDRESS_CITY: String,
  ADDRESS_POSTAL_CODE: String,
  ADDRESS_REGION: String,
  ADDRESS_PROVINCE: String,
  ADDRESS_COUNTRY: String,
  ADDRESS_LOC_ADDR_ID: String,
  UTM_SOURCE: String,
  UTM_MEDIUM: String,
  UTM_CAMPAIGN: String,
  UTM_CONTENT: String,
  UTM_TERM: String,
  LAST_COMMUNICATION_TIME: String,
  LAST_ACTIVITY_BY: String,
  LAST_ACTIVITY_TIME: String
});

module.exports = mongoose.model("Contact", contactSchema);
